hw11/hw9/Models/Cache.cs
using System.ComponentModel.DataAnnotations;

namespace hw9.Models
{
    public class Cache
    {
        [Key]
        public string Expression { get; set; }
        public string Value { get; set; }
    }
}

hw11/hw9/Models/CacheContext.cs
using Microsoft.EntityFrameworkCore;

namespace hw9.Models
{
    public class CacheContext:DbContext
    {
        public DbSet<Cache> Cache { get; set; }

        public CacheContext(DbContextOptions<CacheContext> options) : base(options)
        {
            Database.EnsureCreated();
        }
        
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(local);Database=dbTask;Trusted_Connection=True;");
        }
    }
}

hw11/hw9/Models/ErrorViewModel.cs
using System;

namespace hw9.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

hw11/hw9/Controllers/CalculatorController.cs
using System;
using System.Diagnostics;
using System.Linq.Expressions;
using System.Reflection.Metadata;
using System.Text.RegularExpressions;
using hw9.Models;
using hw9.Calculator;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace hw9.Controllers
{
    public class CalculatorController : Controller
    {
        private readonly ILogger<CalculatorController> _calculator;
        private readonly CacheContext _ctx;
        public CalculatorController(ILogger<CalculatorController> calculator, CacheContext ctx)
        {
            _calculator = calculator;
            _ctx = ctx;
        }
        
        [HttpGet]
        public IActionResult Calculate()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Calculate(string input)
        {
            var calculator = new CachingCalculator(_ctx, new Calculator.Calculator());
            try
            {
                var tree = ExpressionTree.ConvertToBinaryTree(input.Replace(" ", ""));
                var result = calculator.Calculate(tree);
                return Content(result);
            }
            catch (Exception ex)
            {
                return Content($"{ex.Message} :(");
            }
        }

        [HttpGet]
        public ActionResult CalculateU([FromQuery] string expr)
        {
            var calculator = new CachingCalculator(_ctx, new Calculator.Calculator());
            try
            {
                var tree = ExpressionTree.ConvertToBinaryTree(expr.Replace(" ", "+"));
                var result = calculator.Calculate(tree);
                return Content(result);
            }
            catch (Exception ex)
            {
                return Content($"{ex.Message} :(");
            }
        } 
        
        [HttpGet]
        public IActionResult Index()
        {
            return Content("example for filling: \nhttps://localhost:5001/calculator/calculateu?expr=1/2");
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

hw11/hw9/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using hw9.Models;

namespace hw9.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

hw11/hw9/Views/Calculator/Calculate.cshtml
@model hw9.Calculator.CachingCalculator
@using(Html.BeginForm("Calculate", "Calculator", FormMethod.Post))
{
    @Html.EditorForModel()
    <br>
    <input class="btn btn-primary" type="submit" value="Calculate">
                                                                  
}

hw11/hw9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - hw98</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">hw9</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Calculate">Calculator +-*/</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - hw9 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>